from __future__ import annotations
from typing import List, overload

class ShuffleCache: ...

class Signature:
    def __init__(self, order: int = 1, fill_value: complex = 0.0) -> None: ...

    def order(self) -> int: ...

    @overload
    def get_element(self, coordinates: int, coord_order: int) -> complex: ...
    @overload
    def get_element(self, coordinates: List[int]) -> complex: ...

    @overload
    def set_element(self, coordinates: int, coord_order: int, el: complex) -> None: ...
    @overload
    def set_element(self, coordinates: List[int], el: complex) -> None: ...

    def __iadd__(self, other: Signature) -> Signature: ...
    def __isub__(self, other: Signature) -> Signature: ...
    def __imul__(self, scalar: complex) -> Signature: ...
    def __itruediv__(self, scalar: complex) -> Signature: ...

def compute_shuffle_cache(truncation: int) -> ShuffleCache: ...

@overload
def shuffle(left: Signature, right: Signature, truncation: int, cache: ShuffleCache) -> Signature: ...
@overload
def shuffle(left: Signature, right: Signature, truncation: int) -> Signature: ...

def matmul(left: Signature, right: Signature, truncation: int) -> Signature: ...

def bracket(left: Signature, right: Signature) -> complex: ...

def projection_on(sig: Signature, coordinates: int, coord_order: int) -> complex: ...

def to_string(sig: Signature) -> str: ...

__all__ = [
    'ShuffleCache',
    'Signature',
    'bracket',
    'compute_shuffle_cache',
    'matmul',
    'projection_on',
    'shuffle',
    'to_string'
]