# signature_core/signature_core_cpp.pyi
from typing import List, Optional, Tuple, Union
import numpy as np

class Sig2D:
    def __init__(self, order: int = ..., fill_value: complex = ...) -> None: ...
    def order(self) -> int: ...
    def copy(self) -> Sig2D: ...
    def get_element(self, coordinates: int, coord_order: int) -> complex: ...
    def get_element(self, coordinates: List[int]) -> complex: ...
    def set_element(self, coordinates: int, coord_order: int, el: complex) -> None: ...
    def set_element(self, coordinates: List[int], el: complex) -> None: ...

    # In-place operators
    def __iadd__(self, other: 'Sig2D') -> 'Sig2D': ...
    def __imul__(self, scalar: complex) -> 'Sig2D': ...
    def __itruediv__(self, scalar: complex) -> 'Sig2D': ...
    def __isub__(self, other: 'Sig2D') -> 'Sig2D': ...

    # Binary operators
    def __add__(self, other: 'Sig2D') -> 'Sig2D': ...
    def __sub__(self, other: 'Sig2D') -> 'Sig2D': ...
    def __mul__(self, scalar: complex) -> 'Sig2D': ...
    def __truediv__(self, scalar: complex) -> 'Sig2D': ...
    def __rmul__(self, scalar: complex) -> 'Sig2D': ...

    def __str__(self) -> str: ...

class ShuffleCache: ...

def compute_shuffle_cache(truncation: int) -> ShuffleCache: ...
def shuffle(left: Sig2D, right: Sig2D, truncation: int, cache: Optional[ShuffleCache] = None) -> Sig2D: ...
def matmul(left: Sig2D, right: Sig2D, truncation: int) -> Sig2D: ...
def bracket(left: Sig2D, right: Sig2D) -> complex: ...
def projection_on(sig: Sig2D, coordinates: int, coord_order: int) -> Sig2D: ...
def to_string(sig: Sig2D) -> str: ...